<?php
/** @var \MGS\AjaxCart\Block\Ui\Related $block */

if (($items = $block->getItems()) && $items->count()):
    $title = __('Products you might like!');
?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php $_imagehelper = $this->helper('Magento\Catalog\Helper\Image'); ?>
<?php $size = $themeHelper->getImageMinSize(); ?>
    <div class="block popup__related">
        <div class="block-title title text-center margin-bottom15 text-uppercase">
            <h5 id="block-related-heading" role="heading" aria-level="2"><?php echo $block->escapeHtml($title); ?></h5>
        </div>
        <div class="block-content content" aria-labelledby="block-related-heading">
            <div class="products wrapper grid products-grid products-related">
                <div data-related-block="items" class="products list items product-items owl-carousel">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $item): ?>
                        <?php $available = ''; ?>

                        <?php if (!$item->isComposite() && $item->isSaleable()): ?>
                            <?php if (!$item->getRequiredOptions()): ?>
                                <?php $available = 'related-available'; ?>
                            <?php endif; ?>
                        <?php endif; ?>
                        <div class="item product product-item">
							<div class="product-item-info <?php  /* @noEscape */ echo $available; ?>">
								<a href="<?php echo $block->escapeUrl($block->getProductUrl($item)) ?>"
								   class="product photo product-item-photo">
									<?php $productImage = $_imagehelper->init($item, 'product_small_image')->resize($size['width'], $size['height'])->getUrl(); ?>
									<img src="<?php echo $productImage; ?>" alt="<?php echo $block->escapeHtml($item->getName()) ?>" class="img-responsive"/>
								</a>
								<div class="product details product-item-details">
									<strong class="product name product-item-name">
										<a class="product-item-link" title="<?php echo $block->escapeHtml($item->getName()) ?>" href="<?php echo $block->escapeUrl($block->getProductUrl($item)) ?>">
											<?php echo $block->escapeHtml($item->getName()) ?>
										</a>
									</strong>
									<?php /* @escapeNotVerified */ echo $block->getProductPrice($item); ?>
								</div>
							</div>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
        </div>
    </div>

	<script type="text/javascript">
		require([
			'jquery',
			'mgs/owlcarousel'
		], function ($) {
            $('.popup__related .products.list.product-items').owlCarousel({
                items: 2,
                autoplay: true,
                loop: true,
                autoplayHoverPause: true,
                nav: false,
                rtl: RTL,
                dots: true
            });
		});
	</script>
<script type="text/x-magento-init">
    {
        ".popup__related button.action.tocart": {
            "widgetAddToCart": {
                "formKey": <?php /* @noEscape */ echo $block->getFormKey() ?>
            }
        }
    }
</script>
<script>
    require([
        'jquery',
        'mage/mage'
    ], function($, widgetAddToCart) {
        $(document).ajaxComplete(function(event, xhr) {
            if (xhr.responseText) {
                try {
                    eval("var json = " + xhr.responseText + " || {}");
                } catch (e) {
                    return;
                }
            }
        });
    });

</script>
<?php endif;?>
