<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data') ?>
<?php $canUsePanel = $themeHelper->acceptToUsePanel() ?>

<?php // Get footer version ?>
<?php $footer = $themeHelper->getStoreConfig('mgstheme/footer/footer'); ?>
<?php if($footer == 'footer' || $footer == ""): ?><?php $footer = 'footer_1'; ?><?php endif ?>

<?php // Footer content ?>
<div class="footer-container">
    <?php // Footer 1 ?>
    <?php if($footer == 'footer_1'): ?>
        <?php // Middle Footer ?>
        <div class="middle-footer">
            <div class="container">
                <div class="middle-footer--content">
                    <div class="row">
                        <?php //Static block ninth_middle_footer_1_block_contact ?>
                        <div class="col-lg-6 col-md-6 col-xs-12 margin-bottom30">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_middle_footer_1_block_contact')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <?php //Static block ninth_middle_footer_1_block_categories ?>
                        <div class="mdft-block col-lg-2 col-md-2 col-sm-4 col-xs-12 margin-bottom30">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_middle_footer_1_block_categories')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <?php //Static block ninth_middle_footer_1_block_company ?>
                        <div class="mdft-block col-lg-2 col-md-2 col-sm-4 col-xs-12 margin-bottom30">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_middle_footer_1_block_company')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <?php //Static block ninth_middle_footer_1_block_quicklinks ?>
                        <div class="mdft-block col-lg-2 col-md-2 col-sm-4 col-xs-12 margin-bottom30">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_middle_footer_1_block_quicklinks')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php // Bottom Footer ?>
        <div class="bottom-footer">
            <div class="container">
                <div class="bottom-footer--content">
                    <div class="row">
                        <?php //Static block ninth_bottom_footer_1_payment_icons ?>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 pull-right">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_bottom_footer_1_payment_icons')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <?php // Get config Copyright ?>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <address><?php echo $themeHelper->getStoreConfig('mgstheme/footer/footer_copyright') ?></address>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php elseif($footer == 'footer_2'): ?>
        <div class="bottom-footer">
            <div class="container-fluid">
                <div class="bottom-footer--content">
                    <div class="row">
                        <?php //Static block ninth_bottom_footer_2_social_icons ?>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 pull-right">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_bottom_footer_2_social_icons')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <?php // Get config Copyright ?>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <address><?php echo $themeHelper->getStoreConfig('mgstheme/footer/footer_copyright') ?></address>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php elseif($footer == 'footer_3'): ?>  
        <div class="top-footer">
            <div class="container">
                <div class="top-footer--content">
                    <div class="footer-aboutus">
                        <?php //Static block ninth_top_footer_3_block_about_us ?>
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_top_footer_3_block_about_us')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>
                </div>
            </div>
        </div>
        <?php // Middle Footer ?>
        <div class="middle-footer">
            <div class="container">
                <div class="middle-footer--content">
                    <div class="row">
                        <?php //Static block ninth_middle_footer_3_block_categories ?>
                        <div class="mdft-block col-lg-3 col-md-3 col-sm-6 col-xs-12 margin-bottom30">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_middle_footer_3_block_categories')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <?php //Static block ninth_middle_footer_3_block_company ?>
                        <div class="mdft-block col-lg-3 col-md-3 col-sm-6 col-xs-12 margin-bottom30">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_middle_footer_3_block_company')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <?php //Static block ninth_middle_footer_3_block_quicklinks ?>
                        <div class="mdft-block col-lg-3 col-md-3 col-sm-6 col-xs-12 margin-bottom30 first-sm-item">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_middle_footer_3_block_quicklinks')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <?php //Static block ninth_middle_footer_3_block_address ?>
                        <div class="mdft-block col-lg-3 col-md-3 col-sm-6 col-xs-12 margin-bottom30">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_middle_footer_3_block_address')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php // Bottom Footer ?>
        <div class="bottom-footer">
            <div class="container">
                <div class="bottom-footer--content">
                    <div class="row">
                        <?php //Static block ninth_bottom_footer_1_payment_icons ?>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 pull-right">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_bottom_footer_1_payment_icons')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <?php // Get config Copyright ?>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <address><?php echo $themeHelper->getStoreConfig('mgstheme/footer/footer_copyright') ?></address>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php elseif($footer == 'footer_4'): ?>   
        <div class="middle-footer">
            <div class="container-fluid">
                <div class="middle-footer--content">
                    <div class="footer-horizontal-menu">
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_bottom_footer_4_menu_links')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>
                    <div class="logo-footer">
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_bottom_footer_4_logo')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>
                    <div class="footer-horizontal-menu text-right">
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_bottom_footer_4_social_links')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>
                </div>
            </div>
        </div> 
        <div class="bottom-footer">
            <div class="container-fluid">
                <div class="bottom-footer--content">
                    <div class="row">
                        <?php //Static block ninth_bottom_footer_1_payment_icons ?>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 pull-right">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_bottom_footer_1_payment_icons')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <?php // Get config Copyright ?>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <address><?php echo $themeHelper->getStoreConfig('mgstheme/footer/footer_copyright') ?></address>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    <?php elseif($footer == 'footer_5'): ?>
        <div class="footer-social--content">
            <?php //echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_footer_5_social')->setCanUsePanel($canUsePanel)->toHtml() ?>
        </div>
        <div class="top-footer">
            <div class="container-fluid">
                <div class="top-footer--content">
                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_footer_5_newsletter')->setCanUsePanel($canUsePanel)->toHtml() ?>
                </div>
            </div>
        </div>
        <?php // Middle Footer ?>
        <div class="middle-footer">
            <div class="container-fluid">
                <div class="middle-footer--content">
                    <div class="row">
                        <?php //Static block ninth_middle_footer_5_block_contact ?>
                        <div class="col-lg-3 col-md-4 col-xs-12 margin-bottom30">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_middle_footer_5_block_contact')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <?php //Static block ninth_middle_footer_5_menu_1 ?>
                        <div class="mdft-block col-lg-2 col-md-2 col-sm-3 col-xs-12 margin-bottom30">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_middle_footer_5_menu_1')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <?php //Static block ninth_middle_footer_5_menu_2 ?>
                        <div class="mdft-block col-lg-2 col-md-2 col-sm-3 col-xs-12 margin-bottom30">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_middle_footer_5_menu_2')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <?php //Static block ninth_middle_footer_5_menu_3 ?>
                        <div class="mdft-block col-lg-2 col-md-2 col-sm-3 col-xs-12 margin-bottom30">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_middle_footer_5_menu_3')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <?php //Static block ninth_middle_footer_5_menu_4 ?>
                        <div class="mdft-block col-lg-3 col-md-2 col-sm-3 col-xs-12 margin-bottom30">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_middle_footer_5_menu_4')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php // Bottom Footer ?>
        <div class="bottom-footer">
            <div class="container-fluid">
                <div class="bottom-footer--content">
                    <div class="row">
                        <?php //Static block ninth_bottom_footer_1_payment_icons ?>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 pull-right">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_bottom_footer_1_payment_icons')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <?php // Get config Copyright ?>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <address><?php echo $themeHelper->getStoreConfig('mgstheme/footer/footer_copyright') ?></address>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php elseif($footer == 'footer_6'): ?>
        <div class="middle-footer">
            <div class="container-fluid">
                <div class="middle-footer--content">
                    <div class="footer-horizontal-menu">
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_bottom_footer_6_menu_links')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>
                    <div class="logo-footer">
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_bottom_footer_6_logo')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>
                    <div class="footer-horizontal-menu text-right">
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_bottom_footer_6_social_links')->setCanUsePanel($canUsePanel)->toHtml() ?>
                    </div>
                </div>
            </div>
        </div> 
        <div class="bottom-footer">
            <div class="container-fluid">
                <div class="bottom-footer--content">
                    <div class="row">
                        <?php //Static block ninth_bottom_footer_1_payment_icons ?>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 pull-right">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_bottom_footer_1_payment_icons')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <?php // Get config Copyright ?>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <address><?php echo $themeHelper->getStoreConfig('mgstheme/footer/footer_copyright') ?></address>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
   <?php elseif($footer == 'footer_7'): ?>
        <?php // Middle Footer ?>
        <div class="middle-footer">
            <div class="container-fluid">
                <div class="middle-footer--content">
                    <div class="row">
                        <?php //Static block ninth_middle_footer_5_block_contact ?>
                        <div class="col-lg-6 col-md-6 col-xs-12 margin-bottom30">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_middle_footer_5_block_contact')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <?php //Static block ninth_middle_footer_5_menu_1 ?>
                        <div class="mdft-block col-lg-2 col-md-2 col-sm-4 col-xs-12 margin-bottom30">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_middle_footer_5_menu_1')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <?php //Static block ninth_middle_footer_5_menu_2 ?>
                        <div class="mdft-block col-lg-2 col-md-2 col-sm-4 col-xs-12 margin-bottom30">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_middle_footer_5_menu_2')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <?php //Static block ninth_middle_footer_5_menu_3 ?>
                        <div class="mdft-block col-lg-2 col-md-2 col-sm-4 col-xs-12 margin-bottom30">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_middle_footer_5_menu_3')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php // Bottom Footer ?>
        <div class="bottom-footer">
            <div class="container-fluid">
                <div class="bottom-footer--content">
                    <div class="row">
                        <?php //Static block ninth_bottom_footer_1_payment_icons ?>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 pull-right">
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ninth_bottom_footer_1_payment_icons')->setCanUsePanel($canUsePanel)->toHtml() ?>
                        </div>
                        <?php // Get config Copyright ?>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <address><?php echo $themeHelper->getStoreConfig('mgstheme/footer/footer_copyright') ?></address>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php else: ?>
        <div class="footer-container">
            <section class="bottom-footer">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    <?php endif ?>
    <div class="text-center">
        <?php echo $this->getLayout()->createBlock('Magento\Store\Block\Switcher')->setTemplate('switch/stores.phtml')->toHtml() ?>
    </div>
</div>
<script type="text/javascript">
    require(['jquery'],function( $ ) {
        $(".mdft-block .title").click(function(){
            if($(window).width() < 768){
                $(this).parent().toggleClass('active');
                $(this).parent().find('.content').slideToggle();
            }
        });
    });
</script>