<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>

<?php // Helper ?>
<?php $_imagehelper = $this->getImageHelper(); ?>
<?php $themeHelper = $this->getThemeHelper(); ?>
<?php $quickViewHelper = $this->getQuickViewHelper(); ?>
<?php $_helper = $this->getCatalogHelperOutput(); ?>
<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>

<?php // Product item & attribute ?>
<?php $_product = $this->getProduct(); ?>
<?php $lazyLoad = $this->setLazyLoad(); ?>
<?php $baseImage = $hoverBaseImage = $this->getLazyLoadBaseImage(); ?>
<?php $ratio = $this->getRatio(); ?>
<?php $productUrl = $_product->getProductUrl(); ?>
<?php $change_img = $this->getHoverChange(); ?>

<div class="product-item-info" data-container="product-grid">
	<?php // Product Top ?>
	<div class="product-top">
		<?php 
            $size = $this->getSize();
			$productImage = $_imagehelper->init($_product, 'category_page_grid')->resize($size['width'], $size['height'])->getUrl();
            if(!$lazyLoad){
                $baseImage = $productImage;
            }
            
            if($change_img){
                $productImageHover = $_imagehelper->init($_product, 'product_thumbnail_image')->resize($size['width'], $size['height'])->getUrl();
                if(!$lazyLoad){
                    $hoverBaseImage = $productImageHover;
                }
            }
		?>
		<a href="<?php echo $productUrl ?>" class="product photo product-item-photo" style="padding-bottom: <?php echo $this->getPadding(); ?>;"  tabindex="-1">
        
            <?php $imgAlt = $block->stripTags($_product->getName(), null, true); ?>
            
			<img src="<?php echo $baseImage ?>" alt="<?php echo $imgAlt; ?>" class="img-responsive product-image-photo img-thumbnail<?php if($lazyLoad): ?> lazy<?php endif ?>" data-src="<?php echo $productImage ?>"/>
            
            <?php if($change_img): ?>
                <?php if(basename($_product->getData('thumbnail')) !=  'no_selection'): ?>
                    <?php if(basename($_product->getData('thumbnail')) != basename($_product->getData('small_image'))): ?>
                        <img src="<?php echo $hoverBaseImage ?>" alt="<?php echo $imgAlt ?>" class="img-responsive img-hover-show<?php if($lazyLoad): ?> lazy<?php endif ?>" data-src="<?php echo $productImageHover ?>" />
                    <?php endif ?>
                <?php endif ?>
            <?php endif ?>
            
			<div class="product-image-photo"></div>
            
		</a>
		
		<?php // Product Label ?>
		<?php echo $themeHelper->getProductLabel($_product) ?>
		
		<div class="product-detail-action">
			<?php // Add to cart ?>
			<div class="actions-link button">
				<?php if ($_product->isSaleable()): ?>
					<?php $postParams = $this->getPostParams(); ?>
					<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
						<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
						<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
						<?php echo $this->getFk(); ?>
						<button type="submit" data-title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart btn btn-xs">
							<span class="text"><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
							<span class="icon pe-7s-shopbag"></span>
						</button>
					</form>
				<?php else: ?>
					<button class="action tocart btn btn-xs disabled" type="button" data-title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
						<span class="text"><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
						<span class="icon pe-7s-shopbag"></span>
					</button>
				<?php endif; ?>
			</div>
			 
			<?php // Wishlist  ?>
			<?php if ($this->getWishList()): ?>
				<button class="action towishlist"
				   data-title="<?php echo __('Add to Wish List') ?>"
				   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
				   data-post='<?php /* @escapeNotVerified */ echo $this->getWishListPost(); ?>'
				   data-action="add-to-wishlist"
				   role="button">
					<i class="pe-7s-like"></i>
				</button>
			<?php endif; ?>
            
			<?php // Compare  ?>
			<?php if($this->getCompare()): ?>
				<button class="action tocompare"
				   data-title="<?php echo __('Add to Compare') ?>"
				   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
				   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
				   role="button">
					<i class="pe-7s-graph3"></i>
				</button>
			<?php endif ?>
            
			<?php // QuickView  ?>
			<?php echo $quickViewHelper->aroundQuickViewHtml($_product, $ratio); ?>

		</div>
	</div>
	
	<?php // Product Detail ?>
	<div class="product details product-item-details">
	
		<div class="product-detail-content">
            
			<?php // Product Name ?>
			<div class="product name product-item-name" data-name="E">
				<a class="product-item-link"
				   href="<?php /* @escapeNotVerified */ echo $productUrl ?>">
					<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
				</a>
			</div>
            
            <?php echo $this->getReview(); ?>
            
            <?php $ct_attr = $this->getCustomAttribute(); ?>
            <?php $attribute_text = ""; ?>
            <?php if($ct_attr): ?>
                <?php $attribute_text = $_product->getAttributeText($ct_attr); ?>
            <?php endif ?>
            
            <div class="<?php if (!$_product->isSaleable()): ?>ost-product <?php endif ?>actions-and-attr<?php echo $attribute_text ? '' : ' no-attribute'; ?>">
            
                <?php if($ct_attr): ?>
                    <div class="ct-attribute-text<?php if(!$attribute_text): ?> empty<?php endif ?>"><?php echo $attribute_text ?></div>
                <?php endif ?>
                
            </div>
            
            <?php echo $this->getSwatches(); ?>
		</div>
        
        <div class="product-detail-price">
            <?php echo $this->getPrdPrice() ?>
        </div>
        
	</div>
</div>