<?php $categories = $this->getCategoryByIds() ?>

<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$settings = $themeHelper->getThemeSettings();
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$quickViewHelper = $this->helper('MGS\QuickView\Helper\Data');
?>

<?php
// Backend Config
$ct_attr = $themeHelper->getStoreConfig('ninththeme/ninth_catalog/attribute_text');
$display_overlay = $themeHelper->getStoreConfig('ninththeme/ninth_catalog/display_overlay');
$change_img = $themeHelper->getStoreConfig('ninththeme/ninth_catalog/change_img');
$grid_tp = $themeHelper->getStoreConfig('ninththeme/ninth_catalog/grid_type');
if($grid_tp == ""){ $grid_tp = 1; }
$lazyLoad = $themeHelper->getStoreConfig('mgstheme/general/lazy_load');
$onePr = $themeHelper->getStoreConfig('ninththeme/ninth_catalog/one_product');
$mbItem = $onePr ? 1 : 2;
?>

<?php
$showCompare = $settings['catalog']['compare_button'] ? false : true;
$showWishList = $settings['catalog']['wishlist_button'] && $this->helper('Magento\Wishlist\Helper\Data')->isAllow() ? false : true;
?>

<div class="content-block product-tab category-product-cat-block category-product-cat-tab-block">

	<?php // Block Title ?>
	<?php if($this->getData('mgs_panel_title') != "" || $this->getData('mgs_panel_note') != ""): ?>
		<div class="content-heading">
			<?php if($this->getData('mgs_panel_note') != ""): ?>
				<div class="sub-title"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_note')) ?></div>
			<?php endif ?>
			<?php if($this->getData('mgs_panel_title') != ""): ?>
				<h3 class="title"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_title')) ?></h3>
			<?php endif ?>
		</div>
	<?php endif ?>
	
	<?php // Block Content  ?>
	<?php if(count($categories)>0): ?>
		<?php 
			$blockId = rand() . time();
			$_helper = $this->helper('Magento\Catalog\Helper\Output');
			$useSlider = $this->getUseSlider();
			$perRow = $this->getPerrow();
			if($useSlider && $this->hasData('number_row') && $this->getNumberRow()>1){
				$columnCount = $perRow * $this->getNumberRow();
			}
			$image = 'category_page_grid';
			$themeSettings = $themeHelper->getThemeSettings();
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			$col = $themeHelper->convertPerRowtoCol($perRow);
			$autoPlay = $this->getAutoplay() ? 'true' : 'false';
			$stopAuto = $this->getStopAuto() ? 'true' : 'false';
			$nav = $this->getNavigation() ? 'true' : 'false';
			$dot = $this->getPagination() ? 'true' : 'false';
			
		?>
        
		<?php $ratio = $this->getRatio(); ?>
        <?php $size = $themeHelper->getImageSize($ratio); ?>
		<?php $padding = $themeHelper->getImagePadding($ratio); ?>
        <?php $baseImage = $this->getViewFileUrl('MGS_Mpanel::images/blank'.$ratio.'.png'); ?>
        <?php $fk = $block->getBlockHtml('formkey'); ?>
		
		
		<div class="tabbable">
            <div class="menu-tab">
                <div class="show-menu-product-tabs hidden-lg hidden-md" id="show-menu-product-tabs" data-menutogle="#menu-product-tabs<?php echo $blockId ?>">
                    <?php echo __('Categories'); ?>
                </div>
                <ul id="menu-product-tabs<?php echo $blockId ?>" class="nav nav-tabs menu-product-tabs">
                    <?php $i=0; foreach($categories as $category): $i++ ?>
                        <li<?php if($i==1): ?> class="active"<?php endif ?>>
                            <a data-toggle="tab" href="#category-tab-<?php echo $category->getId().$blockId ?>"><?php echo $category->getName(); ?></a>
                        </li>
                    <?php endforeach ?>
                </ul>
            </div>
			<div class="tab-content">
				<?php $i=0; foreach($categories as $category): $i++ ?>
					<div id="category-tab-<?php echo $category->getId().$blockId ?>" class="products-grid template-v3 tab-pane<?php if($i==1): ?>  active<?php endif ?>">
						<div class="category-product-category-tab" id="category<?php echo $category->getId().$blockId; ?>-category-products">
							<?php $_productCollection = $this->getProductCollection($category); ?>
							<?php if (count($_productCollection)>0): ?>
							
								<?php $_imagehelper = $this->helper('Magento\Catalog\Helper\Image'); ?>
								
								<div class="block widget mgs-products category-products-grid products-grid">
									<!-- Don't Remove Id of this div element -->
									<div id="category-products<?php echo $category->getId().$blockId; ?>" class="items">
										
										<?php $j=0; foreach ($_productCollection as $_product): $j++; ?>
                                        
                                            <?php $review = $block->getReviewsSummaryHtml($_product, \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW); ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <?php $prdPrice = $block->getProductPrice($_product) ?>
                                            <?php $swatches = $this->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setProduct($_product)->setTemplate('Magento_Swatches::product/listing/renderer.phtml')->toHtml() ?>
                                            <?php $wlDataPost = $block->getAddToWishlistParams($_product); ?>
                                            <?php $pos = $block->getPositioned(); ?>
                                            
                                            <?php if($j % 9 < 6 && $j % 9 != 0): ?>
                                                <?php if($j % 9 == 1): ?>
                                                <div class="row">
                                                <?php endif ?>
                                                    <?php if($j % 9 < 5): ?>
                                                    <?php if($j % 9 == 1): ?>
                                                    <div class="col-md-6 col-xs-12">
                                                    <div class="row">
                                                    <?php endif ?>
                                                        <div class="product grid-template-<?php echo $grid_tp ?> product-item col-sm-6 col-xs-6">
                                                            <?php echo $this->getLayout()
                                                                    ->createBlock('Magento\Framework\View\Element\Template')
                                                                    ->setProduct($_product)
                                                                    ->setThemeHelper($themeHelper)
                                                                    ->setImageHelper($_imagehelper)
                                                                    ->setCatalogHelperOutput($_helper)
                                                                    ->setQuickViewHelper($quickViewHelper)
                                                                    ->setRatio($ratio)
                                                                    ->setSize($size)
                                                                    ->setCustomAttribute($ct_attr)
                                                                    ->setPadding($padding)
                                                                    ->setLazyLoadBaseImage($baseImage)
                                                                    ->setCompare($showCompare)
                                                                    ->setFk($fk)
                                                                    ->setPostParams($postParams)
                                                                    ->setReview($review)
                                                                    ->setPrdPrice($prdPrice)
                                                                    ->setWishList($showWishList)
                                                                    ->setLazyLoad($lazyLoad)
                                                                    ->setHoverChange($change_img)
                                                                    ->setWishListPost($wlDataPost)
                                                                    ->setTemplate('MGS_Mpanel::products/grid_item/grid_item_'.$grid_tp.'.phtml')
                                                                    ->setSwatches($swatches)
                                                                    ->setPos($pos)
                                                                    ->toHtml(); ?>
                                                        </div>
                                                    <?php if($j % 9 == 4 || $j == count($_productCollection)): ?>
                                                    </div>
                                                    </div>
                                                    <?php endif ?>
                                                    <?php endif ?>
                                                    <?php if($j % 9 == 5): ?>
                                                    <div class="col-md-6 col-xs-12">
                                                        <div class="product grid-template-<?php echo $grid_tp ?> product-item">
                                                                <?php echo $this->getLayout()
                                                                        ->createBlock('Magento\Framework\View\Element\Template')
                                                                        ->setProduct($_product)
                                                                        ->setThemeHelper($themeHelper)
                                                                        ->setImageHelper($_imagehelper)
                                                                        ->setCatalogHelperOutput($_helper)
                                                                        ->setQuickViewHelper($quickViewHelper)
                                                                        ->setRatio($ratio)
                                                                        ->setSize($size)
                                                                        ->setCustomAttribute($ct_attr)
                                                                        ->setPadding($padding)
                                                                        ->setLazyLoadBaseImage($baseImage)
                                                                        ->setCompare($showCompare)
                                                                        ->setFk($fk)
                                                                        ->setPostParams($postParams)
                                                                        ->setReview($review)
                                                                        ->setPrdPrice($prdPrice)
                                                                        ->setWishList($showWishList)
                                                                        ->setLazyLoad($lazyLoad)
                                                                        ->setHoverChange($change_img)
                                                                        ->setWishListPost($wlDataPost)
                                                                        ->setTemplate('MGS_Mpanel::products/grid_item/grid_item_'.$grid_tp.'.phtml')
                                                                        ->setSwatches($swatches)
                                                                        ->setPos($pos)
                                                                        ->toHtml(); ?>
                                                        </div>
                                                    </div>
                                                    <?php endif ?>
                                                <?php if($j % 9 == 5 || $j == count($_productCollection)): ?>
                                                </div>
                                                <?php endif ?>
                                            <?php else: ?>
                                                <?php if($j % 9 == 6): ?>
                                                <div class="row">
                                                <?php endif ?>
                                                    <div class="product grid-template-<?php echo $grid_tp ?> product-item col-md-3 col-xs-6">
                                                       <?php echo $this->getLayout()
                                                                    ->createBlock('Magento\Framework\View\Element\Template')
                                                                    ->setProduct($_product)
                                                                    ->setThemeHelper($themeHelper)
                                                                    ->setImageHelper($_imagehelper)
                                                                    ->setCatalogHelperOutput($_helper)
                                                                    ->setQuickViewHelper($quickViewHelper)
                                                                    ->setRatio($ratio)
                                                                    ->setSize($size)
                                                                    ->setCustomAttribute($ct_attr)
                                                                    ->setPadding($padding)
                                                                    ->setLazyLoadBaseImage($baseImage)
                                                                    ->setCompare($showCompare)
                                                                    ->setFk($fk)
                                                                    ->setPostParams($postParams)
                                                                    ->setReview($review)
                                                                    ->setPrdPrice($prdPrice)
                                                                    ->setWishList($showWishList)
                                                                    ->setLazyLoad($lazyLoad)
                                                                    ->setHoverChange($change_img)
                                                                    ->setWishListPost($wlDataPost)
                                                                    ->setTemplate('MGS_Mpanel::products/grid_item/grid_item_'.$grid_tp.'.phtml')
                                                                    ->setSwatches($swatches)
                                                                    ->setPos($pos)
                                                                    ->toHtml(); ?>
                                                    </div>
                                                <?php if($j % 9 == 0 || $j == count($_productCollection)): ?>
                                                </div>
                                                <?php endif ?>
                                            <?php endif ?>
                                                
										<?php endforeach; ?>
									</div>
									<?php if($useSlider): ?>
										<script type="text/javascript">
											require([
												'jquery',
												'mgs/owlcarousel'
											], function ($) {
												var owlnewcattab<?php echo $category->getId().$blockId ?> = $('#category-products<?php echo $category->getId().$blockId ?>').owlCarousel({
													<?php if($slideMultiRow): ?>
														items: 1,
													<?php else: ?>
														items: <?php echo $perRow; ?>,
													<?php endif ?>
													autoplay: <?php echo $autoPlay ?>,
													<?php if($lazyLoad): ?>lazyLoad: true,<?php endif ?>
													autoplayHoverPause: <?php echo $stopAuto ?>,
													nav: <?php echo $nav ?>,
													dots: <?php echo $dot ?>,
                                                    rtl: RTL,
													navText: ["<i class='pe-7s-angle-left'></i>","<i class='pe-7s-angle-right'></i>"],
													<?php if(!$slideMultiRow):?>
														responsive:{
															0:{
																items:1
															},
															480:{
																items:2
															},
															768:{
																items:<?php echo $perRow; ?>
															}
														}
													<?php endif ?>
												});
											});
										</script>
									<?php endif ?>
								</div>
							<?php else: ?>
								<div role="alert" class="alert alert-warning"> <?php echo __('The category "%1" haven\'t product.', $category->getName()) ?> </div>
							<?php endif ?>
						</div>
						
						<?php if ((count($_productCollection)>0) && !$useSlider): ?>
							<?php if(($this->hasData('loadmore') && $this->getData('loadmore')=='1') && ((!$this->getData('limit')) || (count($_productCollection) == $this->getData('limit')))): ?>
								<div class="loadmore-action">
									<a id="loadmore-btn-<?php echo $category->getId().$blockId ?>" class="btn-loadmore" href="<?php echo $this->getUrl('mpanel/index/loadmore', ['type'=>'category-products-category', 'category'=>$category->getId(), 'perrow'=>$perRow, 'limit'=>$this->getLimit(), 'ratio'=>$this->getRatio(), 'col'=>$col, 'block_id'=>$blockId, 'tabs'=>1, 'p'=>2]) ?>">
										<span class="dot">.</span><span class="dot">.</span><span class="dot">.</span>
										<span class="text"><?php echo __('Load More') ?></span>
										<span class="text load-text"><?php echo __('Loading') ?></span>
										<span class="dot">.</span><span class="dot">.</span><span class="dot">.</span>
									</a>
								</div>
							<?php endif ?>
						<?php endif ?>
					</div>
				<?php endforeach ?>
			</div>
		</div>
        <script type="text/javascript">
            require([
                'jquery'
            ], function(jQuery){
                (function($) {
                    $(document).ready(function() {
                        $(document).on("click","#show-menu-product-tabs",function(e){
                            var toggleElement = $(this).attr('data-menutogle');
                            $(toggleElement).slideToggle('slow');
                        });
                        $(document).on("click",".menu-product-tabs a",function(e){
                            if($(window).width() < 992){
                                $(this).parent().parent().slideUp('slow');
                            }
                        });
                    });
                })(jQuery);
            });
        </script>
	<?php else: ?>
		<div role="alert" class="alert alert-warning"><?php echo __('There are no categories matching the selection.') ?></div>
	<?php endif ?>
</div>