<?php // Product Collection ?>
<?php $_productCollection = $this->getCategoryProductByIds($this->getCategoryIds()) ?>

<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$settings = $themeHelper->getThemeSettings();
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$quickViewHelper = $this->helper('MGS\QuickView\Helper\Data');
?>

<?php
// Backend Config
$ct_attr = $themeHelper->getStoreConfig('ninththeme/ninth_catalog/attribute_text');
$display_overlay = $themeHelper->getStoreConfig('ninththeme/ninth_catalog/display_overlay');
$change_img = $themeHelper->getStoreConfig('ninththeme/ninth_catalog/change_img');
$grid_tp = $themeHelper->getStoreConfig('ninththeme/ninth_catalog/grid_type');
if($grid_tp == ""){ $grid_tp = 1; }
$lazyLoad = $themeHelper->getStoreConfig('mgstheme/general/lazy_load');
$onePr = $themeHelper->getStoreConfig('ninththeme/ninth_catalog/one_product');
$mbItem = $onePr ? 1 : 2;
?>

<?php
$showCompare = $settings['catalog']['compare_button'] ? false : true;
$showWishList = $settings['catalog']['wishlist_button'] && $this->helper('Magento\Wishlist\Helper\Data')->isAllow() ? false : true;
?>

<div class="content-block category-product-cat-block">
	<?php // Block Title ?>
	<?php if($this->getData('mgs_panel_title') != "" || $this->getData('mgs_panel_note') != ""): ?>
		<div class="content-heading">
			<?php if($this->getData('mgs_panel_note') && $this->getData('mgs_panel_note') != ""): ?>
				<div class="sub-title"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_note')) ?></div>
			<?php endif ?>
			<?php if($this->getData('mgs_panel_title') && $this->getData('mgs_panel_title') != ""): ?>
				<h2 class="title"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_title')) ?></h2>
			<?php endif ?>
		</div>
	<?php endif ?>
	
	<?php // Block Content  ?>
	<?php if (count($_productCollection)): ?>
		
		<?php $ratio = $this->getRatio(); ?>
        <?php $size = $themeHelper->getImageSize($ratio); ?>
		<?php $padding = $themeHelper->getImagePadding($ratio); ?>
        <?php $baseImage = $this->getViewFileUrl('MGS_Mpanel::images/blank'.$ratio.'.png'); ?>
        <?php $fk = $block->getBlockHtml('formkey'); ?>
        
		<?php $blockId = rand() . time(); ?>
		<?php $useSlider = $this->getUseSlider(); ?>
		<?php $perRow = $this->getPerrow(); ?>
		<?php $col = $themeHelper->convertPerRowtoCol($perRow); ?>
		
		<?php if($useSlider && $this->hasData('number_row') && $this->getNumberRow()>1): ?>
			<?php $slideMultiRow = true; ?>
			<?php $columnCount = $perRow * $this->getNumberRow(); ?>
		<?php else: ?>
			<?php $slideMultiRow = false; ?>
		<?php endif ?>
		
		<div class="block widget mgs-products category-products-grid<?php echo $display_overlay ? ' display_overlay' : '' ?><?php echo $onePr ? ' mobile-1-product' : '' ?> products-grid <?php if($useSlider): ?>row<?php if(!$slideMultiRow): ?> slider-1-row<?php endif ?><?php endif ?>">
			<div id="category-products<?php echo $blockId; ?>" 
				class="items<?php if($useSlider): ?> owl-carousel<?php else: ?> row <?php echo $themeHelper->convertColClass($col, 'row') ?><?php endif ?>">
				<?php $i=0; $j=0; foreach ($_productCollection as $_product): $i++; ?>
                
					<?php $review = $block->getReviewsSummaryHtml($_product, \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW); ?>
                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                    <?php $prdPrice = $block->getProductPrice($_product) ?>
                    <?php $swatches = $this->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setProduct($_product)->setTemplate('Magento_Swatches::product/listing/renderer.phtml')->toHtml() ?>
                    <?php $wlDataPost = $block->getAddToWishlistParams($_product); ?>
                    <?php $pos = $block->getPositioned(); ?>
                    
					<?php if($slideMultiRow): ?>
						<?php if ($j++ % $columnCount == 0): ?>
						<div class="item">
						<?php endif ?>
					<?php endif ?>
					
							<div class="product grid-template-<?php echo $grid_tp ?> product-item <?php if($slideMultiRow || !$this->hasData('number_row')): ?><?php echo $themeHelper->getClearClass($perRow, $i) ?> <?php echo $themeHelper->convertColClass($col, 'col') ?><?php endif ?>">
								<?php echo $this->getLayout()
                                    ->createBlock('Magento\Framework\View\Element\Template')
                                    ->setProduct($_product)
                                    ->setThemeHelper($themeHelper)
                                    ->setImageHelper($_imagehelper)
                                    ->setCatalogHelperOutput($_helper)
                                    ->setQuickViewHelper($quickViewHelper)
                                    ->setRatio($ratio)
                                    ->setSize($size)
                                    ->setCustomAttribute($ct_attr)
                                    ->setPadding($padding)
                                    ->setLazyLoadBaseImage($baseImage)
                                    ->setCompare($showCompare)
                                    ->setFk($fk)
                                    ->setPostParams($postParams)
                                    ->setReview($review)
                                    ->setPrdPrice($prdPrice)
                                    ->setWishList($showWishList)
                                    ->setLazyLoad($lazyLoad)
                                    ->setHoverChange($change_img)
                                    ->setWishListPost($wlDataPost)
                                    ->setTemplate('MGS_Mpanel::products/grid_item/grid_item_'.$grid_tp.'.phtml')
                                    ->setSwatches($swatches)
                                    ->setPos($pos)
                                    ->toHtml(); ?>
							</div>
							
					<?php if($slideMultiRow): ?>
						<?php if ($j % $columnCount == 0 || $j == count($_productCollection)): ?>
						</div>
						<?php endif ?>
					<?php endif ?>
					
				<?php endforeach; ?>
			</div>
		</div>
		
		<?php if($useSlider): ?>
			<?php $autoPlay = $this->getAutoplay() ? 'true' : 'false'; ?>
			<?php $stopAuto = $this->getStopAuto() ? 'true' : 'false'; ?>
			<?php $nav = $this->getNavigation() ? 'true' : 'false'; ?>
			<?php $dot = $this->getPagination() ? 'true' : 'false'; ?>
			
			<script type="text/javascript">
				require([
					'jquery',
					'mgs/owlcarousel'
				], function ($) {
					var owlnewcattab<?php echo $blockId ?> = $('#category-products<?php echo $blockId ?>').owlCarousel({
						<?php if($slideMultiRow): ?>
							items: 1,
						<?php else: ?>
							items: <?php echo $perRow; ?>,
						<?php endif ?>
						autoplay: <?php echo $autoPlay ?>,
						<?php if($lazyLoad): ?>lazyLoad: true,<?php endif ?>
						autoplayHoverPause: <?php echo $stopAuto ?>,
						nav: <?php echo $nav ?>,
						dots: <?php echo $dot ?>,
                        rtl: RTL,
						<?php if(!$slideMultiRow): ?>
						responsive:{
							0:{
								items: <?php echo $mbItem ?>,
                                slideBy: <?php echo $mbItem ?>,
								nav: false,
								dots: true
							},
							768:{
								items:<?php echo $perRow; ?>
							}
						},
						<?php endif ?>
						navText: ["<i class='pe-7s-angle-left'></i>","<i class='pe-7s-angle-right'></i>"],
					});
				});
			</script>
		<?php else: ?>
			<?php if (count($_productCollection)>0): ?>
				<?php if(($this->hasData('loadmore') && $this->getData('loadmore')=='1') && ((!$this->getData('limit')) || (count($_productCollection)== $this->getData('limit')))): ?>
					<div class="loadmore-action"><a class="btn-loadmore" href="<?php echo $this->getUrl('mpanel/index/loadmore', ['type'=>'category-products-category', 'category'=>$this->getCategoryIds(), 'perrow'=>$perRow, 'limit'=>$this->getLimit(), 'ratio'=>$this->getRatio(), 'col'=>$col, 'block_id'=>$blockId, 'tabs'=>0, 'p'=>2]) ?>">
							<span class="dot">.</span><span class="dot">.</span><span class="dot">.</span>
                            <span class="text"><?php echo __('Load More') ?></span>
                            <span class="text load-text"><?php echo __('Loading') ?></span>
                            <span class="dot">.</span><span class="dot">.</span><span class="dot">.</span>
						</a></div>
				<?php endif ?>
			<?php endif ?>
		<?php endif ?>
	<?php else: ?>
		<div role="alert" class="alert alert-warning"><?php echo __('There are no products matching the selection.') ?></div>
	<?php endif ?>
</div>