<?php
/**
 * Copyright © 2015 MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>

<?php
    $isCityDbType = $this->helper('MageWorx\GeoIP\Helper\Database')->isCityDbType();
?>
<?php if ($_item = $this->getItem()): ?>
    <?php $_geoip = $_item->getGeoIp() ?>
    <?php if ($_item->getIp()): ?>
        <?php echo $block->escapeHtml($_item->getIp()) ?>
    <?php endif; ?>
    <?php if ($_item->getXforwarderfor()): ?>
        <?php echo $block->escapeHtml(' (' . $_item->getXforwarderfor() . ')') ?>
    <?php endif; ?>
    <?php if ($_geoip->getCode()): ?>
        <?php if ($_geoip->getFlag()): ?>
            <img class="v-middle" src="<?php echo $block->escapeHtml($_geoip->getFlag()) ?>" title="<?php echo $block->escapeHtml($_geoip->getCode()) ?>" />
        <?php endif; ?>
        <?php echo $block->escapeHtml($_geoip->getCode()) ?>, <?php echo $block->escapeHtml($_geoip->getCountry()) ?>
        <?php if ($isCityDbType): ?>
            <?php echo $block->escapeHtml(implode(', ', array_filter(array($_geoip->getRegion(), $_geoip->getCity(), $_geoip->getPostalCode())))) ?>
        <?php endif; ?>
    <?php else: ?>
        <?php echo __('n/a') ?>
    <?php endif; ?>
<?php endif; ?>