<script type="text/javascript">
	require([
		'jquery',
		'mgs/lazyload'
	], function(jQuery){
		(function($) {
            $(document).ready(function() {
               $("img.lazy").unveil(25, function(){
                    var self = $(this);
                    setTimeout(function(){
                        self.removeClass('lazy');
                        self.parent().addClass('lz-loaded');
                    }, 0);
                });
            });
		})(jQuery);
	});
</script>