<?php $_productCollection = $this->getDealsByCategories($this->getCategoryIds()) ?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>

<?php $lazyLoad = $themeHelper->getStoreConfig('mgstheme/general/lazy_load'); ?>
<?php $baseImage = $this->getViewFileUrl('MGS_Mpanel::images/blank'.$this->getRatio().'.png'); ?>
<?php $dateTimeFormat = \Magento\Framework\Stdlib\DateTime::DATETIME_PHP_FORMAT; ?>
<?php $now = $themeHelper->getCurrentDateTime(); ?>

<div class="content-block">
	<?php if($this->getData('mgs_panel_title') != "" || $this->getData('mgs_panel_note') != ""): ?>
		<div class="content-heading">
			<?php if($this->getData('mgs_panel_title')): ?>
				<h3 class="title"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_title')) ?></h3>
			<?php endif ?>
			<?php if($this->getData('mgs_panel_note')): ?>
				<p><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_note')) ?></p>
			<?php endif ?>
		</div>
	<?php endif ?>
	
	<?php if (count($_productCollection)>0): ?>
		
		<?php 
			$blockId = rand() . time();
			$_helper = $this->helper('Magento\Catalog\Helper\Output');
			$useSlider = $this->getUseSlider();
			$perRow = $this->getPerrow();
			if($useSlider && $this->hasData('number_row') && $this->getNumberRow()>1){
				$columnCount = $perRow * $this->getNumberRow();
			}
			$limit = $this->getLimit();
			$image = 'category_page_grid';
			$_image = 'product_thumbnail_image';
			$size = $themeHelper->getImageSize($this->getRatio());
			$themeSettings = $themeHelper->getThemeSettings();
			$padding = $themeHelper->getImagePadding($this->getRatio());
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			$col = $themeHelper->convertPerRowtoCol($perRow);
			$autoPlay = $this->getAutoplay() ? 'true' : 'false';
			$stopAuto = $this->getStopAuto() ? 'true' : 'false';
			$nav = $this->getNavigation() ? 'true' : 'false';
			$dot = $this->getPagination() ? 'true' : 'false';
		?>
		
		<div class="block widget mgs-products big-deal-products">
			<div class="items<?php if($useSlider): ?> owl-carousel<?php endif ?>" id="deal-products<?php echo $blockId; ?>">
				<?php $i=0; $j=0; foreach ($_productCollection as $_product): $i++; ?>
					
					<?php if($i <= $limit): ?>
				
					<div class="item product product-item">
						<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
						<div class="product-item-info" data-container="product-grid">
							<?php
								$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
								$productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();
								$productImageHover = $_imagehelper->init($_product, $_image)->resize($size['width'], $size['height'])->getUrl();
								if(!$lazyLoad){
									$baseImage = $productImage;
								}
							?>
							<div class="product-left">
								<?php // Product Image ?>
								<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" style="padding-top: <?php echo $padding; ?>;" class="product photo product-item-photo" tabindex="-1">
									<img src="<?php echo $baseImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo img-thumbnail<?php if($lazyLoad): ?> <?php if($useSlider): ?>owl-<?php endif ?>lazy<?php endif ?>" data-src="<?php echo $productImage ?>"/>
                                    <div class="product-image-photo"></div>
								</a>
							</div>
                            <div class="product-right product details product-item-details">
                                <h5 class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </h5>
                                
                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                
                                <?php if($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description')): ?>
                                    <div class="product-item-description">
                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    </div>
                                <?php endif ?>
                                
                                <?php $specialFromDate = date($dateTimeFormat, strtotime($_product->getSpecialFromDate())); ?>
                                <?php $specialToDate = date($dateTimeFormat, strtotime($_product->getSpecialToDate())); ?>
                                <?php if($specialFromDate <= $now && $specialToDate > $now): ?>
                                    <?php echo $this->getLayout()
                                                    ->createBlock('Magento\Framework\View\Element\Template')
                                                    ->setProduct($_product)
                                                    ->setTimeNow($now)
                                                    ->setSpecialFromDate($specialFromDate)
                                                    ->setSpecialToDate($specialToDate)
                                                    ->setTemplate('MGS_Mpanel::products/deals/countdown.phtml')
                                                    ->toHtml() ?>
                                <?php endif ?>
                                
								<?php if ($_product->isSaleable()): ?>
                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $this->getUrl('checkout/cart/add', ['uenc'=>$postParams['data']['uenc'], 'product'=>$postParams['data']['product']]); ?>" method="post">
                                        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                        <input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
                                        <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
                                        <button class="action tocart btn btn-primary btn-cart" type="submit" data-title="<?php echo __('Add to Cart') ?>" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                            <span class="text"><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                        </button>
                                    </form>
								<?php endif; ?>
                            </div>
						</div>
					</div>
					
					<?php endif; ?>
					
				<?php endforeach; ?>
			</div>
			
			<?php if($useSlider): ?>
				<script type="text/javascript">
					require([
						'jquery',
						'mgs/owlcarousel'
					], function ($) {
						$('#deal-products<?php echo $blockId ?>').owlCarousel({
                            items: 1,
                            singleItem: true,
							autoplay: <?php echo $autoPlay ?>,
							loop: false,
							<?php if($lazyLoad): ?>lazyLoad: true,<?php endif ?>
							autoplayHoverPause: <?php echo $stopAuto ?>,
							nav: <?php echo $nav ?>,
							dots: <?php echo $dot ?>,
                            animateOut: 'fadeOut',
                            animateIn: 'fadeIn',
                            rtl: RTL,
							navText: ["<?php echo __('PREV') ?>","<?php echo __('NEXT') ?>"],
						});
					});
				</script>
			<?php endif ?>
		</div>	
	<?php else: ?>
		<div role="alert" class="alert alert-warning"><?php echo __('There are no deals matching the selection.') ?></div>
	<?php endif ?>
</div>