<?php $_productCollection = $this->getDealsByCategories($this->getCategoryIds()) ?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>

<?php $lazyLoad = $themeHelper->getStoreConfig('mgstheme/general/lazy_load'); ?>
<?php $baseImage = $this->getViewFileUrl('MGS_Mpanel::images/blank'.$this->getRatio().'.png'); ?>
<?php $dateTimeFormat = \Magento\Framework\Stdlib\DateTime::DATETIME_PHP_FORMAT; ?>
<?php $now = $themeHelper->getCurrentDateTime(); ?>

<div class="content-block deal-no-image-products">
	<?php if($this->getData('mgs_panel_title') != "" || $this->getData('mgs_panel_note') != ""): ?>
			<?php if($this->getData('mgs_panel_title')): ?>
				<div class="sub-title"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_title')) ?></div>
			<?php endif ?>
	<?php endif ?>
	
	<?php if (count($_productCollection)>0): ?>
		
		<?php 
			$blockId = rand() . time();
			$_helper = $this->helper('Magento\Catalog\Helper\Output');
			$useSlider = $this->getUseSlider();
			$perRow = $this->getPerrow();
			if($useSlider && $this->hasData('number_row') && $this->getNumberRow()>1){
				$columnCount = $perRow * $this->getNumberRow();
			}
			$limit = $this->getLimit();
			$image = 'category_page_grid';
			$_image = 'product_thumbnail_image';
			$size = $themeHelper->getImageSize($this->getRatio());
			$themeSettings = $themeHelper->getThemeSettings();
			$padding = $themeHelper->getImagePadding($this->getRatio());
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			$col = $themeHelper->convertPerRowtoCol($perRow);
			$autoPlay = $this->getAutoplay() ? 'true' : 'false';
			$stopAuto = $this->getStopAuto() ? 'true' : 'false';
			$nav = $this->getNavigation() ? 'true' : 'false';
			$dot = $this->getPagination() ? 'true' : 'false';
		?>
		
		<div class="block widget mgs-products">
			<div class="items<?php if($useSlider): ?> owl-carousel<?php endif ?>" id="deal-products<?php echo $blockId; ?>">
				<?php $i=0; $j=0; foreach ($_productCollection as $_product): $i++; ?>
					
					<?php if($i <= $limit): ?>
				
					<div class="item product product-item">
						<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
						<div class="product-item-info" data-container="product-grid">
							<?php
								$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
								$productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();
								$productImageHover = $_imagehelper->init($_product, $_image)->resize($size['width'], $size['height'])->getUrl();
								if(!$lazyLoad){
									$baseImage = $productImage;
								}
							?>
                            <div class="product-right product details product-item-details">
                                <h3 class="product-name">
                                    <a class="product-item-link"
                                       href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </h3>
                                
                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                
                                <?php if($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description')): ?>
                                    <div class="product-item-description">
                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    </div>
                                <?php endif ?>
                                
                                <?php $specialFromDate = date($dateTimeFormat, strtotime($_product->getSpecialFromDate())); ?>
                                <?php $specialToDate = date($dateTimeFormat, strtotime($_product->getSpecialToDate())); ?>
                                <?php if($specialFromDate <= $now && $specialToDate > $now): ?>
									<div class="product-timer">
										<i class="pe-7s-clock"></i>
										<?php echo $this->getLayout()
														->createBlock('Magento\Framework\View\Element\Template')
														->setProduct($_product)
														->setTimeNow($now)
														->setSpecialFromDate($specialFromDate)
														->setSpecialToDate($specialToDate)
														->setTemplate('MGS_Mpanel::products/deals/countdown.phtml')
															->toHtml() ?>
										<div class="clearfix"></div>
									</div>
								<?php endif ?>
                                <a class="action-shop-now"
								    href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
									<span> <?php echo __('SHOP NOW') ?></span>
								</a>
                            </div>
						</div>
					</div>
					
					<?php endif; ?>
					
				<?php endforeach; ?>
			</div>
			
			<?php if($useSlider): ?>
				<script type="text/javascript">
					require([
						'jquery',
						'mgs/owlcarousel'
					], function ($) {
						$('#deal-products<?php echo $blockId ?>').owlCarousel({
                            items: 1,
                            singleItem: true,
							autoplay: <?php echo $autoPlay ?>,
							loop: false,
							<?php if($lazyLoad): ?>lazyLoad: true,<?php endif ?>
							autoplayHoverPause: <?php echo $stopAuto ?>,
							nav: <?php echo $nav ?>,
							dots: <?php echo $dot ?>,
                            animateOut: 'fadeOut',
                            animateIn: 'fadeIn',
                            rtl: RTL,
							navText: ["<?php echo __('PREV') ?>","<?php echo __('NEXT') ?>"],
						});
					});
				</script>
			<?php endif ?>
		</div>	
	<?php else: ?>
		<div role="alert" class="alert alert-warning"><?php echo __('There are no deals matching the selection.') ?></div>
	<?php endif ?>
</div>